name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '5.9'

    - name: Build
      run: swift build

    - name: Test
      run: swift test
